export const ERROR_CODES = {
  AUTH_REQUIRED: "AUTH_REQUIRED",
  RBAC_DENIED: "RBAC_DENIED",
  VALIDATION_FAILED: "VALIDATION_FAILED",
  RATE_LIMITED: "RATE_LIMITED",
  PLAN_NOT_FOUND: "PLAN_NOT_FOUND",
  PLAN_NOT_SUBMITTED: "PLAN_NOT_SUBMITTED",
  REJECT_REASON_REQUIRED: "REJECT_REASON_REQUIRED",
  RELIC_NOT_FOUND: "RELIC_NOT_FOUND"
} as const;
